# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\19722\Desktop\Coding\GithubProjects\MyProjects\xiaoya-whut\src\App\ui\new_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_Tab.setGeometry(QtCore.QRect(100, 70, 631, 431))
        self.Main_Tab.setStyleSheet("QTabBar::tab {\n"
"   height: 45px;\n"
"    width:80px;\n"
"  font-size: 18px;\n"
"  padding: 10px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"     background-color: lightblue;\n"
"}\n"
"QTabBar::tab:hover {\n"
"   background-color: lightyellow;\n"
"}")
        self.Main_Tab.setObjectName("Main_Tab")
        self.Welcome_Tab = QtWidgets.QWidget()
        self.Welcome_Tab.setObjectName("Welcome_Tab")
        self.welcome_text = QtWidgets.QTextBrowser(self.Welcome_Tab)
        self.welcome_text.setGeometry(QtCore.QRect(160, 70, 321, 91))
        self.welcome_text.setObjectName("welcome_text")
        self.logout_button = QtWidgets.QPushButton(self.Welcome_Tab)
        self.logout_button.setGeometry(QtCore.QRect(250, 220, 111, 41))
        self.logout_button.setObjectName("logout_button")
        self.label_7 = QtWidgets.QLabel(self.Welcome_Tab)
        self.label_7.setGeometry(QtCore.QRect(-20, 0, 651, 361))
        self.label_7.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    opacity: 0.1;\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.welcome_text.raise_()
        self.logout_button.raise_()
        self.Main_Tab.addTab(self.Welcome_Tab, "")
        self.Information_Tab = QtWidgets.QWidget()
        self.Information_Tab.setEnabled(True)
        self.Information_Tab.setObjectName("Information_Tab")
        self.courses_chooser_message = QtWidgets.QComboBox(self.Information_Tab)
        self.courses_chooser_message.setGeometry(QtCore.QRect(100, 30, 191, 41))
        self.courses_chooser_message.setObjectName("courses_chooser_message")
        self.courses_chooser_message.addItem("")
        self.task_type_chooser = QtWidgets.QComboBox(self.Information_Tab)
        self.task_type_chooser.setGeometry(QtCore.QRect(410, 30, 181, 41))
        self.task_type_chooser.setObjectName("task_type_chooser")
        self.task_type_chooser.addItem("")
        self.label = QtWidgets.QLabel(self.Information_Tab)
        self.label.setGeometry(QtCore.QRect(0, 20, 101, 61))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"楷体\";\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Information_Tab)
        self.label_2.setGeometry(QtCore.QRect(310, 20, 101, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-family: \"楷体\";\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.course_message_scrollArea = QtWidgets.QScrollArea(self.Information_Tab)
        self.course_message_scrollArea.setGeometry(QtCore.QRect(10, 70, 581, 251))
        self.course_message_scrollArea.setWidgetResizable(True)
        self.course_message_scrollArea.setObjectName("course_message_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.course_message_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.course_message_progressBar = QtWidgets.QProgressBar(self.Information_Tab)
        self.course_message_progressBar.setGeometry(QtCore.QRect(10, 10, 611, 23))
        self.course_message_progressBar.setProperty("value", 24)
        self.course_message_progressBar.setObjectName("course_message_progressBar")
        self.Main_Tab.addTab(self.Information_Tab, "")
        self.Resource_Tab = QtWidgets.QWidget()
        self.Resource_Tab.setObjectName("Resource_Tab")
        self.resource_type_chooser = QtWidgets.QComboBox(self.Resource_Tab)
        self.resource_type_chooser.setGeometry(QtCore.QRect(410, 30, 181, 41))
        self.resource_type_chooser.setIconSize(QtCore.QSize(80, 80))
        self.resource_type_chooser.setObjectName("resource_type_chooser")
        self.resource_type_chooser.addItem("")
        self.label_5 = QtWidgets.QLabel(self.Resource_Tab)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 101, 61))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: \"楷体\";\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.course_chooser_resource = QtWidgets.QComboBox(self.Resource_Tab)
        self.course_chooser_resource.setGeometry(QtCore.QRect(100, 30, 191, 41))
        self.course_chooser_resource.setObjectName("course_chooser_resource")
        self.course_chooser_resource.addItem("")
        self.label_6 = QtWidgets.QLabel(self.Resource_Tab)
        self.label_6.setGeometry(QtCore.QRect(310, 20, 101, 61))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: \"楷体\";\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.resource_scrollArea = QtWidgets.QScrollArea(self.Resource_Tab)
        self.resource_scrollArea.setGeometry(QtCore.QRect(10, 70, 581, 251))
        self.resource_scrollArea.setWidgetResizable(True)
        self.resource_scrollArea.setObjectName("resource_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 579, 249))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.resource_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.resource_progressBar = QtWidgets.QProgressBar(self.Resource_Tab)
        self.resource_progressBar.setGeometry(QtCore.QRect(10, 10, 611, 23))
        self.resource_progressBar.setProperty("value", 24)
        self.resource_progressBar.setObjectName("resource_progressBar")
        self.Main_Tab.addTab(self.Resource_Tab, "")
        self.Config_Tab = QtWidgets.QWidget()
        self.Config_Tab.setObjectName("Config_Tab")
        self.checkBox = QtWidgets.QCheckBox(self.Config_Tab)
        self.checkBox.setGeometry(QtCore.QRect(70, 70, 251, 51))
        self.checkBox.setStyleSheet("font: 16pt \"黑体\";\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.Main_Tab.addTab(self.Config_Tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Main_Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小雅助手"))
        self.welcome_text.setMarkdown(_translate("MainWindow", "欢迎\n"
"\n"
""))
        self.welcome_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:7.2pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:4px; margin-bottom:4px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">欢迎</p></body></html>"))
        self.logout_button.setText(_translate("MainWindow", "退出登录"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.Welcome_Tab), _translate("MainWindow", "欢迎"))
        self.courses_chooser_message.setItemText(0, _translate("MainWindow", "全部"))
        self.task_type_chooser.setItemText(0, _translate("MainWindow", "全部"))
        self.label.setText(_translate("MainWindow", "课程名称："))
        self.label_2.setText(_translate("MainWindow", "作业类型："))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.Information_Tab), _translate("MainWindow", "课程信息"))
        self.resource_type_chooser.setItemText(0, _translate("MainWindow", "全部"))
        self.label_5.setText(_translate("MainWindow", "课程名称："))
        self.course_chooser_resource.setItemText(0, _translate("MainWindow", "全部"))
        self.label_6.setText(_translate("MainWindow", "资源类型："))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.Resource_Tab), _translate("MainWindow", "课程资源"))
        self.checkBox.setText(_translate("MainWindow", "不知道放什么设置"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.Config_Tab), _translate("MainWindow", "设置"))
